name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature/initial-setup

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy src to root
      run: cp -r src/* .
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./